### PR TITLE
TOMEE-2368-example-mvc-resteasy

### PR DESCRIPTION
**Pull request by Daniel-Dos**
https://issues.apache.org/jira/browse/TOMEE-2368

I made a simple hello world example with MVC 1.0 using RestEasy module .

### CODE REVIEW

**Comment by radcortez** [comment]
@Daniel-Dos can you please fix the conflict? Thank you!

**Comment by Daniel-Dos** [comment]
Hi @radcortez ,

I can yes. 

thanks.

**Comment by Daniel-Dos** [comment]
done.

**Comment by josehenriqueventura** [comment]
Thank you guys for the effort.

**Pull request merged**
