### PR TITLE
[TOMEE-4061] TomEE 9.x dependencies update: hsqldb 2.7.1, jackson, etc. - MERGE FIRST

### PR DESCRIPTION
**Pull request by sultan**
TomEE 9.x dependencies update: 
- [TOMEE-4096](https://issues.apache.org/jira/browse/TOMEE-4096) Tomcat 10.0.27
- [TOMEE-4086](https://issues.apache.org/jira/browse/TOMEE-4086) HSQLDB 2.7.1
- [TOMEE-4095](https://issues.apache.org/jira/browse/TOMEE-4095) jackson databind 2.13.4.2
- Derby 10.14.2.0
- [TOMEE-4093](https://issues.apache.org/jira/browse/TOMEE-4093) Hibernate 6.1.4.Final
- [TOMEE-4097](https://issues.apache.org/jira/browse/TOMEE-4097) MicroProfile Fault Tolerance API 4.0.2
- [TOMEE-4098](https://issues.apache.org/jira/browse/TOMEE-4098) MicroProfile Health API 4.0.1
- [TOMEE-4099](https://issues.apache.org/jira/browse/TOMEE-4099) MicroProfile Rest Client API 3.0.1

### CODE REVIEW

**Comment by rzo1** [comment]
@sultan In TomEE 9.x (baseline J11) we might be able to go for derby 10.15

**Comment by sultan** [comment]
> @sultan In TomEE 9.x (baseline J11) we might be able to go for derby 10.15

yes but the build currently fails with 10.15

i prefer to make a separated PR for this one

**Comment by sultan** [comment]
rebased/squashed

**Comment by sultan** [comment]
@rzo1 javadoc can be updated to reflect this merge:
* PR https://github.com/apache/tomee-site-generator/pull/51

**Pull request merged**
