### PR TITLE
TOMEE-2612 - updated  javaee-api to 8.0-1

### PR DESCRIPTION
**Pull request by cesarhernandezgt**

### CODE REVIEW

**Comment by rzo1** [comment]
We need to resolve MR conflics, I guess :)

**Comment by rzo1** [comment]
We are on the way to `8.0-2` so this PR needs an update :)

**Comment by rzo1** [comment]
As `8.0-2` is ready now, we should update this PR and the JIRA to reflect latest changes :)

**Comment by jgallimore** [comment]
@cesarhernandezgt Is this PR still needed?

**Comment by cesarhernandezgt** [comment]
> @cesarhernandezgt Is this PR still needed?

We can close this PR. But I'll update TomEE since it seems now apart from the version we also need to fix the maven version format: https://github.com/apache/tomee/blob/master/examples/access-timeout-meta/pom.xml#L57

**Pull request closed without merging**
