### PR TITLE
[TOMEE-4061] TomEE 9.x + Derby 10.15.2.0, upon other dependencies update

### PR DESCRIPTION
**Pull request by sultan**
This is a tentative to update Derby to 10.15.x, upon other dep updates.

Derby 10.15.x is modular, it might break CI, please merge wisely.

TO BE MERGED AFTER: 
* PR #938 
* PR #953 

TomEE 9.x dependencies update: 
- Derby 10.15.2.0

### CODE REVIEW

**Comment by sultan** [comment]
CI build ok on my fork https://github.com/sultan/tomee/actions/runs/3195891350/jobs/5217111532

**Comment by sultan** [comment]
rebased upon:
* PR #938

**Comment by rzo1** [comment]
@sultan Can you rebase this one? So we can create a CI task for it to see

**Comment by sultan** [comment]
on it.

**Comment by sultan** [comment]
@rzo1, rebased and ready for CI test

**Comment by rzo1** [comment]
Thanks. I created a CI task for it: https://ci-builds.apache.org/job/Tomee/job/TOMEE-4061/

**Comment by rzo1** [comment]
@sultan looks like two regressions:

org.apache.openejb.arquillian.EarWarResourcesXmlTest.(?)

org.apache.openejb.resource.jdbc.driver.AlternateDriverJarTest.testBoth

Might be quick ones: class not found and missing jar.

**Comment by sultan** [comment]
ok i'll see if i can correct

**Comment by rzo1** [comment]
If you need help/support, just drop a message in the list or in the PR.

**Comment by sultan** [comment]
@jeanouii updated this test last year for it to pass, i hard coded the test so that the 'two drivers' are 10.10 and 10.14.
you both might want to review this change.

**Comment by sultan** [comment]
rebased upon dependencies cleanup, i do recommend:
* review about the hard coded values of the multi-driver datasources tests
* build on CI

**Comment by sultan** [comment]
TODO : 
* create a JIRA for this dep update

**Comment by sultan** [comment]
rebased upon tomee-9.x

please review

**Comment by sultan** [comment]
is this PR still needed ?

**Comment by rzo1** [comment]
Only derby left. I triggered a full build for it.

**Comment by rzo1** [comment]
I think, that we need to port these changes targeting https://github.com/apache/tomee/pull/1005 as well.

**Comment by jeanouii** [comment]
I'm ok to merge this one too. But this is with the view that we may need to revert because of the TCK setup. I remember TCK issues but probably a good time to address those as well. Thanks @sultan

**Comment by sultan** [comment]
> I'm ok to merge this one too. But this is with the view that we may need to revert because of the TCK setup. I remember TCK issues but probably a good time to address those as well. Thanks @sultan

this will be in PR #1021 ... its a small one so no problem reverting it if needed

**Pull request merged**
