### PR TITLE
TOMEE-2324 - Remove Corba ORB APIs from Codebase

### PR DESCRIPTION
**Pull request by rzo1**
# What does this PR do?

As dicussed on the mailing list a few months ago [[1]](https://www.mail-archive.com/dev@tomee.apache.org/msg14097.html), building TomEE with Java 11 fails because of two classes, which depend on CORBA.

The places in the code-base with CORBA related access are:

```
org.apache.openejb.core.OrbFactory
org.apache.openejb.client.corba.Corbas
```
This PR aims to handle these two classes by generating them via ASM at compile-time during the Maven build (as suggested by @dblevins).

For reference, I have attached a version of the decompiled byte-code generated by ASM:

- [OrbFactory.asm.decompiled.txt](https://github.com/apache/tomee/files/5470902/OrbFactory.asm.decompiled.txt)
- [Corbas.asm.decompiled.txt](https://github.com/apache/tomee/files/5470904/Corbas.asm.decompiled.txt)

If this is merged, [[2]](https://github.com/apache/tomee/pull/664) will be obsolete (due to license issues as discussed in [[1]](https://www.mail-archive.com/dev@tomee.apache.org/msg14097.html)].

# References

- [1] https://www.mail-archive.com/dev@tomee.apache.org/msg14097.html
- [2] PR: https://github.com/apache/tomee/pull/664

### CODE REVIEW

**Comment by jgallimore** [comment]
Thanks for doing this. I'll give this a run-through this morning.

**Comment by rzo1** [comment]
> Thanks for doing this. I'll give this a run-through this morning.

Any updates on it? :)

**Comment by jgallimore** [comment]
I ran into some issues, which may have been down to some other stuff checked into the repository. Now that's sorted, let me run it again.

**Comment by rzo1** [comment]
Thanks for the update, John.

**Comment by jgallimore** [comment]
Currently running into this issue:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:26 min
[INFO] Finished at: 2020-11-16T13:32:24Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test (default) on project apache-tomee: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test failed: A required class was missing while executing org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test: javax/xml/bind/JAXBException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-failsafe-plugin:2.20
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/jgallimore/.m2/repository/org/apache/maven/plugins/maven-failsafe-plugin/2.20/maven-failsafe-plugin-2.20.jar
[ERROR] urls[1] = file:/home/jgallimore/.m2/repository/org/apache/maven/surefire/maven-surefire-common/2.20/maven-surefire-common-2.20.jar
[ERROR] urls[2] = file:/home/jgallimore/.m2/repository/org/apache/maven/surefire/surefire-booter/2.20/surefire-booter-2.20.jar
[ERROR] urls[3] = file:/home/jgallimore/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[4] = file:/home/jgallimore/.m2/repository/junit/junit/4.12/junit-4.12.jar
[ERROR] urls[5] = file:/home/jgallimore/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] urls[6] = file:/home/jgallimore/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[7] = file:/home/jgallimore/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[8] = file:/home/jgallimore/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[9] = file:/home/jgallimore/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[10] = file:/home/jgallimore/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[11] = file:/home/jgallimore/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[12] = file:/home/jgallimore/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[13] = file:/home/jgallimore/.m2/repository/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
[ERROR] urls[14] = file:/home/jgallimore/.m2/repository/org/apache/maven/surefire/surefire-api/2.20/surefire-api-2.20.jar
[ERROR] urls[15] = file:/home/jgallimore/.m2/repository/org/apache/maven/surefire/surefire-logger-api/2.20/surefire-logger-api-2.20.jar
[ERROR] urls[16] = file:/home/jgallimore/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.3/maven-plugin-annotations-3.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.apache.tomee:tomee-project:8.0.5-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : javax.xml.bind.JAXBException
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :apache-tomee
```

**Comment by jgallimore** [comment]
Building with JDK8 is fine, the failure above is with JDK11. Looks like a dependency update in the apache-tomee module will fix it.

**Comment by rzo1** [comment]
> Building with JDK8 is fine, the failure above is with JDK11. Looks like a dependency update in the apache-tomee module will fix it.

The `javax/xml/bind/JAXBException`classes  were removed from the JDK; we might need to add the correct dependencies.

**Comment by jgallimore** [comment]
Added the dependency -- getting further.

**Comment by jgallimore** [comment]
@rzo1 Take a look at: https://github.com/rzo1/tomee/pull/1

**Comment by rzo1** [comment]
> @rzo1 Take a look at: [rzo1#1](https://github.com/rzo1/tomee/pull/1)

Looks good to me. Thanks for the updates.

**Comment by rzo1** [comment]
I have merged the related changes into the PR branch.

**Comment by jgallimore** [comment]
Running a full build with tests with that. Fingers crossed.

**Comment by jgallimore** [comment]
This got as far as the CDI TCK, albeit with a small set of test errors, and then hung. We're getting close. I'll paste the build output as a gist.

**Comment by rzo1** [comment]
> This got as far as the CDI TCK, albeit with a small set of test errors, and then hung. We're getting close. I'll paste the build output as a gist.

Thanks for the update, Jon.

**Comment by rzo1** [comment]
@jgallimore Do you have a build output for the failing tests?

**Comment by rmannibucau** [comment]
Maybe two notes checking this PR:

1. generating the bytecode at build time can be an issue (if you check the TODO they will never happen with such an option). It can be trivial to keep the class as a .java, compile it with source=8 or create an org.apache.tomee:corba-integration module released independently (like javaee-api module) and depend on it.
2. current impl moved to systematic reflection which will be slower and a bottleneck (synchronization) if still used

Due to both points, I'd say that either this can be dropped as a feature or it needs some more love. A well working option would be to.

1. create a SPI abstracting this API
2. ensure it is in SystemInstance (keep in mind you can put in system properties or system.properties the spi-qualified-class=implementation to load it)
3. use the SPI through SystemInstance services instead of the reflection

Then the implementation of 1 can be either in a module in the project or not but it can stay in plain java if corba support is still desired.

Indeed just my 2 cts but went that path and it only works for droppable code so thought I would share that feedback ;).

**Comment by rzo1** [comment]
Thanks for the feedback, @rmannibucau.

>  create an org.apache.tomee:corba-integration module released independently (like javaee-api module) and depend on it.

Would be indeed a better solution instead of doing a bytecode party here - did not think of it :)

To clarify, if I understood you correctly regarding the SPI stuff (as I have never done something like this before, but I am excited to learn ;) )

Does that mean to create something like:
```
public interface CorbasProvider {   
Object toStub(final Object obj) throws IOException;
Object connect(final Object obj) throws IOException;
}
public interface OrbFactoryProvider {   
ORBAdapter create();
}
```
and create related entries in `META-INF/services` ?

Bring it to `SystemInstance` (how?) and then do something like

```
SystemInstance.get().getComponent(CorbasProvider.class) 
SystemInstance.get().getComponent(OrbFactoryProvider.class) 
```

in the implementation instead of the reflection party?

**Comment by rmannibucau** [comment]
@rzo1 yes except META-INF/services part, just org.apache.openejb.cxxxxx.CorbasProvider=org.apache.openejb.yyyy.CorbasProviderImpl in system.properties OR an openejb event observer in corba-integration module doing SystemInstance.get().setComponent(....) (easier and automatic probably but both options work). SystemInstance is a SPI holder by design :). This pattern will work for you https://github.com/apache/tomee/blob/8547f730b7c9fc085534a8f5d1f68340154d2cfe/arquillian/arquillian-tomee-common/src/main/java/org/apache/openejb/arquillian/common/BeanDicovererInstaller.java, just need to put the observer fully qualified name in META-INF/org.apache.openejb.extension

**Comment by rzo1** [comment]
I gave it a try at https://github.com/rzo1/tomee/tree/TOMEE-2324-v2 but I am quite unsure if this is what we were talking about. Consequently, I dropped some FIXME/TODO questions.

For this reason, I didn't open a related (new) PR yet. Maybe you can have a look at it?

**Comment by rmannibucau** [comment]
I think API can be in openejb-core spi package, corba impl depends on openejb-core and corba tests move to corba-integration module (we should avoid having a module for this API need IMHO). In tomee itself we add corba-integration module (in lib/) this way all works as before. Except that it looks good to me.

**Comment by rzo1** [comment]
> I think API can be in openejb-core spi package, corba impl depends on openejb-core and corba tests move to corba-integration module (we should avoid having a module for this API need IMHO). In tomee itself we add corba-integration module (in lib/) this way all works as before. Except that it looks good to me.

Thanks for the fastlane feedback. I will try to incoorporate your feedback and update my v2 branch, open a PR for further discussions (if necessary) and might close this PR here.

**Pull request closed without merging**
