### PR TITLE
Update pom.xml to enforce maven version (currently at least 3.9.8)

### PR DESCRIPTION
**Pull request by nrmnrm**
suggested change as of bugs found in maven 3.9.6 in https://issues.apache.org/jira/browse/TOMEE-4416

Using https://maven.apache.org/enforcer/maven-enforcer-plugin (can be used to enforce eg. jdk version as well)

### CODE REVIEW

**Comment by nrmnrm** [comment]
This fails on purpose as discussed in https://issues.apache.org/jira/browse/TOMEE-4416

Detected Maven Version: 3.8.8 is not in the allowed range [3.9.8,)

I can add a range of versions that are supported, but we know that at least 3.9.6 is not working

**Comment by jungm** [comment]
IMO needs some more investigation - is only 3.9.6 bad? Or all versions before it as well?

GitHub actions worked before and now doesn't pass enforcer anymore, so something looks off to me

**Comment by nrmnrm** [comment]
You are using 3.8.8 in your CI tools, so as this worked before I think at least that one and all later than 3.9.6 are fine. Not sure when it broke and for how long in between. Feel free to define a range of mvn versions you want to support, at least 3.9.6 is failing. I can add the to the enforcer plugin

**Comment by jungm** [comment]
Just tested a full build in a clean maven 3.9.6 container (so no custom settings, ~/.m2/repository is not populated etc) and TomEE built fine:
```
[INFO] Reactor Summary for Apache TomEE 10.0.0-M4-SNAPSHOT:
[INFO] 
[INFO] Apache TomEE ....................................... SUCCESS [ 11.862 s]
[INFO] TomEE :: Deps ...................................... SUCCESS [  0.019 s]
[INFO] TomEE :: Deps :: Taglibs Shade ..................... SUCCESS [ 58.547 s]
[INFO] TomEE :: Deps :: Apache Commons DBCP2 shade ........ SUCCESS [  3.701 s]
[INFO] TomEE :: BOMs ...................................... SUCCESS [  0.016 s]
[INFO] TomEE :: BOMs :: JAXB Runtime ...................... SUCCESS [ 11.817 s]
[INFO] TomEE :: Container ................................. SUCCESS [  0.011 s]
[INFO] TomEE :: Container :: Loader ....................... SUCCESS [  3.392 s]
[INFO] TomEE :: Container :: MBean Annotation API ......... SUCCESS [  0.119 s]
[INFO] TomEE :: Container :: JPA Integration .............. SUCCESS [ 23.749 s]
[INFO] TomEE :: Container :: API .......................... SUCCESS [  1.991 s]
[INFO] TomEE :: Container :: Java Agent ................... SUCCESS [  0.115 s]
[INFO] TomEE :: Container :: Java EE ...................... SUCCESS [  3.383 s]
[INFO] TomEE :: Container :: Java EE Accessors ............ SUCCESS [  3.932 s]
[INFO] TomEE :: Container :: Core ......................... SUCCESS [ 45.480 s]
[INFO] TomEE :: TomEE ..................................... SUCCESS [  0.249 s]
[INFO] TomEE :: TomEE :: Bootstrap ........................ SUCCESS [  1.728 s]
[INFO] TomEE :: TomEE :: Config ........................... SUCCESS [  0.320 s]
[INFO] TomEE :: Server .................................... SUCCESS [  0.009 s]
[INFO] TomEE :: Server :: Client .......................... SUCCESS [  6.470 s]
[INFO] TomEE :: TomEE :: Common ........................... SUCCESS [  0.522 s]
[INFO] TomEE :: TomEE :: Juli ............................. SUCCESS [  4.268 s]
[INFO] TomEE :: TomEE :: Loader ........................... SUCCESS [  0.589 s]
[INFO] TomEE :: TomEE :: JDBC ............................. SUCCESS [  0.615 s]
[INFO] TomEE :: Server :: Core ............................ SUCCESS [  1.404 s]
[INFO] TomEE :: Server :: Multicast Discovery ............. SUCCESS [  0.482 s]
[INFO] TomEE :: Server :: EJBd ............................ SUCCESS [  4.108 s]
[INFO] TomEE :: Server :: Http ............................ SUCCESS [  9.738 s]
[INFO] TomEE :: TomEE :: Catalina ......................... SUCCESS [  1.918 s]
[INFO] TomEE :: Server :: REST ............................ SUCCESS [  0.384 s]
[INFO] TomEE :: Server :: CXF Transport ................... SUCCESS [  7.220 s]
[INFO] TomEE :: Server :: CXF RS .......................... SUCCESS [  7.725 s]
[INFO] TomEE :: Microprofile JWT .......................... SUCCESS [  7.786 s]
[INFO] TomEE :: TomEE :: MicroProfile ..................... SUCCESS [  0.190 s]
[INFO] TomEE :: TomEE :: MicroProfile Common .............. SUCCESS [ 54.125 s]
[INFO] TomEE :: Server :: Webservices ..................... SUCCESS [ 24.563 s]
[INFO] TomEE :: Server :: CXF ............................. SUCCESS [ 55.582 s]
[INFO] TomEE :: Server :: Hsql ............................ SUCCESS [  0.318 s]
[INFO] TomEE :: TomEE :: RS Web Services .................. SUCCESS [  0.648 s]
[INFO] TomEE :: TomEE :: Mojarra .......................... SUCCESS [  2.070 s]
[INFO] TomEE :: TomEE :: MyFaces .......................... SUCCESS [  1.295 s]
[INFO] TomEE :: TomEE :: Util ............................. SUCCESS [  0.267 s]
[INFO] TomEE :: TomEE :: Web Services ..................... SUCCESS [  0.923 s]
[INFO] TomEE :: TomEE :: TomEE Embedded ................... SUCCESS [ 19.051 s]
[INFO] TomEE :: Utils ..................................... SUCCESS [  0.008 s]
[INFO] TomEE :: Utils :: Mockito .......................... SUCCESS [  5.194 s]
[INFO] TomEE :: TomEE :: Security ......................... SUCCESS [  9.126 s]
[INFO] TomEE :: TomEE :: MicroProfile Webapp .............. SUCCESS [ 21.535 s]
[INFO] TomEE :: BOMs :: TomEE MicroProfile ................ SUCCESS [  3.051 s]
[INFO] TomEE :: TomEE :: Webapp ........................... SUCCESS [  4.961 s]
[INFO] TomEE :: BOMs :: TomEE WebProfile .................. SUCCESS [  0.495 s]
[INFO] TomEE :: Utils :: Core EclipseLink ................. SUCCESS [  0.225 s]
[INFO] TomEE :: TomEE :: Plume Webapp ..................... SUCCESS [  4.223 s]
[INFO] TomEE :: BOMs :: TomEE Plume ....................... SUCCESS [  0.793 s]
[INFO] TomEE :: TomEE :: Plus Webapp ...................... SUCCESS [  3.200 s]
[INFO] TomEE :: BOMs :: TomEE Plus ........................ SUCCESS [  0.719 s]
[INFO] TomEE :: BOMs :: TomEE MicroProfile API ............ SUCCESS [  0.085 s]
[INFO] TomEE :: BOMs :: TomEE WebProfile API .............. SUCCESS [  0.054 s]
[INFO] TomEE :: BOMs :: TomEE Plume API ................... SUCCESS [  0.080 s]
[INFO] TomEE :: BOMs :: TomEE Plus API .................... SUCCESS [  0.081 s]
[INFO] TomEE :: Maven Plugins ............................. SUCCESS [  3.507 s]
[INFO] TomEE :: Maven Plugins :: Util ..................... SUCCESS [  0.602 s]
[INFO] TomEE :: TomEE :: Apache TomEE ..................... SUCCESS [01:25 min]
[INFO] TomEE :: Maven Plugins :: TomEE Maven Plugin ....... SUCCESS [  8.951 s]
[INFO] TomEE :: Utils :: LiveReload ....................... SUCCESS [  0.315 s]
[INFO] TomEE :: Maven Plugins :: TomEE Embedded Maven Plugin SUCCESS [  7.951 s]
[INFO] TomEE :: Maven Plugins :: OpenEJB Embedded Maven Plugin SUCCESS [  1.119 s]
[INFO] TomEE :: Maven Plugins :: TomEE Webapp Archetype ... SUCCESS [  0.083 s]
[INFO] TomEE :: Maven Plugins :: jars.txt Maven Plugin .... SUCCESS [  0.221 s]
[INFO] TomEE :: Maven Plugins :: ApplicationComposer Maven Plugin SUCCESS [  1.934 s]
[INFO] TomEE :: Gradle Plugins ............................ SUCCESS [ 11.297 s]
[INFO] TomEE :: Gradle Plugins :: TomEE Embedded .......... SUCCESS [  0.101 s]
[INFO] TomEE :: Container :: JUnit ........................ SUCCESS [  0.425 s]
[INFO] TomEE :: Container :: JUnit 5 ...................... SUCCESS [  0.339 s]
[INFO] TomEE :: Container :: JUnit 5 :: Backward Compatibility SUCCESS [  0.337 s]
[INFO] TomEE :: Server :: ActiveMQ ........................ SUCCESS [  0.310 s]
[INFO] TomEE :: Server :: Derby Network Service ........... SUCCESS [  1.664 s]
[INFO] TomEE :: Server :: Daemon .......................... SUCCESS [  0.232 s]
[INFO] TomEE :: Server :: Common CLI ...................... SUCCESS [  1.190 s]
[INFO] TomEE :: Server :: SSH ............................. SUCCESS [  3.924 s]
[INFO] TomEE :: Server :: BoneCP .......................... SUCCESS [  2.990 s]
[INFO] TomEE :: Server :: Hessian ......................... SUCCESS [  1.335 s]
[INFO] TomEE :: Assembly .................................. SUCCESS [  0.015 s]
[INFO] TomEE :: Assembly :: Standalone .................... SUCCESS [  3.480 s]
[INFO] TomEE :: Assembly :: All In One EJB Lite jar ....... SUCCESS [ 21.093 s]
[INFO] TomEE :: Arquillian Adaptors Parent ................ SUCCESS [  0.008 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Common ...... SUCCESS [  5.027 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: TomEE Common  SUCCESS [  7.102 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Transaction Provider SUCCESS [  6.379 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Embedded Adaptor SUCCESS [  5.305 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Remote ...... SUCCESS [  5.582 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Webapp Remote SUCCESS [  0.347 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: ZipLock ..... SUCCESS [  9.116 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Tests ....... SUCCESS [  5.527 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Tests :: Web Profile SUCCESS [  6.286 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Tests :: JAXRS SUCCESS [ 51.788 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Tests :: JAXWS SUCCESS [  2.272 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Tests :: JMS  SUCCESS [  1.235 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Tests :: Configuration Tests SUCCESS [  1.204 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Sample :: Moviefun SUCCESS [ 42.278 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: OpenEJB Container SUCCESS [  6.921 s]
[INFO] TomEE :: Arquillian Adaptors Parent :: Arquillian TCK SUCCESS [  2.027 s]
[INFO] TomEE :: Utils :: TomEE Webapps-based Deployer EJB . SUCCESS [  0.225 s]
[INFO] TomEE :: Utils :: Core Hibernate ................... SUCCESS [  4.917 s]
[INFO] TomEE :: Utils :: Provisionning .................... SUCCESS [  0.628 s]
[INFO] TomEE :: Utils :: Log4j2 ........................... SUCCESS [  1.874 s]
[INFO] TomEE :: TomEE :: webaccess ........................ SUCCESS [ 21.326 s]
[INFO] TomEE :: TomEE :: Overlay Runner ................... SUCCESS [  0.244 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:15 min
[INFO] Finished at: 2024-10-16T06:22:21Z
[INFO] ------------------------------------------------------------------------
```

Command I used: `docker run --rm -it --entrypoint bash maven:3.9.6 -c "git clone https://github.com/apache/tomee.git && cd tomee && mvn -Pquick -Dsurefire.useFile=false -DdisableXmlReport=true -DuniqueVersion=false -ff -Dassemble -DskipTests -DfailIfNoTests=false clean install"`

System information:
```
➜ docker run --rm --entrypoint mvn maven:3.9.6 -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /usr/share/maven
Java version: 21.0.3, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.8.0-47-generic", arch: "amd64", family: "unix"
```

**Comment by nrmnrm** [comment]
Hm, not sure why this works for you, I can reproduce failing build with 3.9.6.. Only other differences are jdk version and OS (I am on jdk 17 and windows)

**Pull request closed without merging**
