### PR TITLE
Create java-compatibility.adoc

### PR DESCRIPTION
**Pull request by dineshkumarg**
Maintaining compatibility helps users to know Java versions support for TomEE

### CODE REVIEW

**Comment by cesarhernandezgt** [comment]
I think we can iterate after this PR to actually provide compatibility Matrix into TomEE branches :)
The information is right in the poms so for example, we can provide MicroProfile specific version, Cfx version etc:

https://github.com/apache/tomee/blob/8c6358cca46e431df78fc9c7d818259a9ba8635b/pom.xml#L198-L210

The overall goal is to provide a user friendly version matrix without the need to go into the repository and pom.xml files. We can even automate the process but that could be a third iteration.

**Comment by jeanouii** [comment]
Thank you so much guys for the doc and the collaboration on the document.
Going to merge it

**Comment by jeanouii** [comment]
How about creating another PR for TomEE 8.x (aka master)?
We could update it on a regular basis

**Comment by dineshkumarg** [comment]
> How about creating another PR for TomEE 8.x (aka master)?
> We could update it on a regular basis

Sure, I will create a similar document for TomEE 8.x

Thank you

**Comment by rmonson** [comment]
Hi,
Dinesh.  Do you have any more contact information?  Like an email address?

**Comment by dineshkumarg** [comment]
> Hi,
> Dinesh. Do you have any more contact information? Like an email address?

yes it's dinesh.gaddam@gmail.com

**Pull request merged**
