### PR TITLE
TOMEE-4113 - Update to MicroProfile Metrics 5 & SmallRye Metrics 5

### PR DESCRIPTION
**Pull request by jgallimore**

### CODE REVIEW

**Comment by rzo1** [comment]
@jgallimore What do we need to do here?

**Comment by jgallimore** [comment]
I'll take a look. I did quite a lot of work in this area, so it would be nice to get this over the line.

**Comment by rzo1** [comment]
I just merged in the latest changes from main (from the last years). The Metrics TCK has only 3 failures :)

**Comment by tandraschko** [comment]
did it pass before the upgrade? Otherwise lets merge and try to fix all TCKs after M1?

**Comment by rzo1** [comment]
> did it pass before the upgrade? Otherwise lets merge and try to fix all TCKs after M1?

yes, it was ok ;-)

**Comment by rzo1** [comment]
@jgallimore @tandraschko I expect the PR CI build to be green now, so we can move ahead with integrating this great PR into "main". TCK is passing (aside from 3 tests, which are **optional**) - therefore, I marked them as excluded (for now)

**Comment by rzo1** [comment]
Thanks @jgallimore - TCK for Metrics is good; some of the examples aren't compatible anymore which will be fixed with [TOMEE-4329 - Fix Metrics examples to comply with Metrics 5](https://issues.apache.org/jira/browse/TOMEE-4329)

**Pull request merged**
