### PR TITLE
Updated tomee-patch-plugin to 0.7

### PR DESCRIPTION
**Pull request by cesarhernandezgt**

### CODE REVIEW

**Comment by cesarhernandezgt** [comment]
GH actions is failing but "locally the PR works" XD. 
Jenkins CI executes the test so this is providing different feedback than GH actions.

**Comment by rzo1** [comment]
@cesarhernandezgt Do we have a 0.7 release? If so, the tag / push is missing in https://github.com/apache/tomee-patch-plugin

**Comment by jeanouii** [comment]
@cesarhernandezgt I am very sorry, I was chatting with Richard on slack and he was mentioning the patch plugin issue. I realized I did the release but we never upgraded TomEE with 0.7 so went ahead and updated it.

I just saw your PR after when Richard mentioned it
I'm again very sorry. But I believe we can close this one.

**Comment by jeanouii** [comment]
Here is my commit https://github.com/apache/tomee/commit/9712b375fbbe8e9a759c13dd61aea6ad037b160e
Slightly different because I tried to have the version in one single place and removed an outdated staging repo.

**Comment by cesarhernandezgt** [comment]
> Here is my commit [9712b37](https://github.com/apache/tomee/commit/9712b375fbbe8e9a759c13dd61aea6ad037b160e) Slightly different because I tried to have the version in one single place and removed an outdated staging repo.

No worries, thank you for the follow-up. 
I'm closing now this PR.

**Pull request closed without merging**
