### PR TITLE
TOMEE-2982 Translate to Portuguese: examples/simple-jms-context

### PR DESCRIPTION
**Pull request by Daniel-Dos**
Translate to portuguese the example JMS context .

Link to JIra: https://issues.apache.org/jira/browse/TOMEE-2982

### CODE REVIEW

**Comment by jrxxjr** [comment]
In this phrase "This example demostrate how to set up a ``CustomJmsService`` in order to produce and consume a JMS ``Message``.", have a problem, it is in english.

**Comment by Daniel-Dos** [comment]
thanks @jrxxjr , you can review again ?

**Comment by jrxxjr** [comment]
Now, the translation it is ok.

**Comment by Daniel-Dos** [comment]
thanks @jrxxjr  for review :)

**Pull request merged**
