### PR TITLE
[TOMEE-4109] TomEE 9.x Update velocity to 2.3 and avoid CVE warnings

### PR DESCRIPTION
**Pull request by sultan**
Update dependency
* velocity 2.3

### CODE REVIEW

**Comment by rzo1** [comment]
Can you create a jire?

**Comment by sultan** [comment]
issue created on JIRA, waiting review before this can be merged

**Review by rzo1 — APPROVED** [review]

**Comment by sultan** [comment]
@rzo1, before merging, can you confirm it is ok to lose the LogChute features?

**Comment by sultan** [comment]
Good to go

**Pull request merged**
