### PR TITLE
TOMEE-4164 JSON-B TCK Setup

### PR DESCRIPTION
**Pull request by jeanouii**

### CODE REVIEW

**Comment by jeanouii** [comment]
Closing this one because it's merged into https://github.com/apache/tomee/pull/1005

**Comment by rzo1** [comment]
@jeanouii Guess it is time to rebase? :)

**Comment by rzo1** [comment]
- Signature tests are passing. 
- Currently only one test fails:

```bash
ee.jakarta.tck.json.bind.cdi.customizedmapping.adapters.AdaptersCustomizationCDITest.testCDISupport 
```

**Comment by rzo1** [comment]
This should be good now (both modules pass). @jeanouii can you have a look?

**Pull request merged**
