### PR TITLE
TOMEE-4165 JSON-P TCK setup

### PR DESCRIPTION
**Pull request by jeanouii**

### CODE REVIEW

**Comment by jeanouii** [comment]
Closing this one because it's merged into https://github.com/apache/tomee/pull/1005

**Comment by rzo1** [comment]
@jeanouii Guess it is time to rebase? :)

**Comment by rzo1** [comment]
The standalone TCK looks good, but the signature tests are faile with our jakartaee-api uber jar:

```bash
Some signatures failed.
	Failed packages listed below: 
		jakarta.json(static mode)
		jakarta.json(reflection mode)
	Passed packages listed below: 
		jakarta.json.spi(static mode)
		jakarta.json.spi(reflection mode)
		jakarta.json.stream(static mode)
		jakarta.json.stream(reflection mode)
```

**Comment by rzo1** [comment]
Should be ok now (everything passes).  Please check @jeanouii

**Pull request merged**
