### PR TITLE
Example Project - Kotlin, CDI, JAX-RS

### PR DESCRIPTION
**Pull request by brandonlamb**
DO NOT MERGE YET - WIP

Example includes the following, slightly more than a basic "hello world".

- Kotlin
- CDI (DI and events)
- JAX-RS (including ExceptionMappers for error handling)
- Domain-Driven Design
- Ports and Adapters
- Constructor injection, interfaces
- Dockerfile to build and run in Docker (multi-stage build)

TODO

- Add README documenting the example (need to learn asciidoc first)
- Add tests? Meh. Test in production.

### CODE REVIEW

**Comment by brunobat** [comment]
Please register and send us an email to dev@tomee.apache.org.  We would love to hear from you over there!

**Comment by brunobat** [comment]
Hi @brandonlamb! I don't know if you had the time to take a look at the previous comments...
I also found two more issues:

- You are committing a .gitignore file
- All the files need an Apache 2.0 license. Even the xml ones.

**Comment by dblevins** [comment]
I'm happy to help add headers to the PR or any other things this would need.  Very excited about having a Kotlin example -- never tried it myself :)

**Comment by dblevins** [comment]
@brandonlamb let me know if you don't have time to work on it anymore.  I'll dig in and see what it would take to finish.

**Comment by brandonlamb** [comment]
haha yea at the moment I can't make time to get that last 10% over the finish line. I was out on holiday for this so I had time. Figured I would try to come back at some point but didnt want to leave the project and this PR just hanging in limbo

**Comment by dblevins** [comment]
No worries -- I've spent most my life in that spot (wanting to have time for open source, getting nearly there and losing the time).  In practice, you take progressively bigger tasks, so this dynamic never changes.

What needs to happen for this to "finish"?  (i'd be excited to dig in)

**Pull request closed without merging**
