### PR TITLE
TOMEE-2286 Metrics gauge example

### PR DESCRIPTION
**Pull request by ivanjunckes**
This is WIP since I found a bug while doing this.

### CODE REVIEW

**Comment by radcortez** [comment]
@ivanjunckes can you fix the conflict please?

**Comment by ivanjunckes** [comment]
done @radcortez

**Comment by radcortez** [comment]
Hey @ivanjunckes it needs more conflicts fixing :)

**Comment by dblevins** [comment]
I fixed the merge conflict by deleting the examples/mp-metrics-counted/README.md doc.

If there were changes in there we needed, they need to be created again.

**Pull request merged**
