### PR TITLE
[TOMEE-4053] TomEE 8.x Dependency properties cleanup

### PR DESCRIPTION
**Pull request by sultan**
WIP

Versions not to be upgraded:
* bval = 2.0.5 and not 2.0.6
* cxf = 3.4.8 and not 3.5.4

Removed properties:

    <pax-url.version>1.3.5</pax-url.version>
    <version.wagon>2.2</version.wagon>
    <plexus.version>1.5.5</plexus.version>
    <plexus-utils.version>3.0.10</plexus-utils.version>
    <org.apache.axis2.version>1.4.1</org.apache.axis2.version>
    <scannotation.version>1.0.2</scannotation.version>
    <geronimo-osgi.version>1.1</geronimo-osgi.version>

### CODE REVIEW

**Comment by rzo1** [comment]
@sultan Can you rebase / resolve conflicts? As discussed on the list, we should give it a try.

**Comment by sultan** [comment]
this will take time to be sure i dont remove any dependency update. i will basically do the pr again from the current 8.x branch

**Comment by rzo1** [comment]
Take your time, I am happy to give it a try

**Comment by rzo1** [comment]
@sultan This is (atm) intended, so we should stick with `8.0.14-SNAPSHOT` atm. We (mis)use the examples for integration testing / testing of our container. Perhaps we need to add it to the long list of things to improve in the future.

**Comment by sultan** [comment]
ok reverting

**Comment by sultan** [comment]
yanked eclipse from microprofile name, ready for CI build/tests

**Comment by rzo1** [comment]
https://ci-builds.apache.org/job/Tomee/job/TOMEE-4053/

**Comment by rzo1** [comment]
Looks like we have some regressions after these changes: https://ci-builds.apache.org/job/Tomee/job/TOMEE-4053/6/
Some failures might be race conditions, some might be regressions, but I guess it needs some digging :)

**Comment by sultan** [comment]
@rzo1 I feel like this can be done via multiple short PRs. i will make another one with only the reordering/regrouping and without name changes

**Comment by rzo1** [comment]
Yeah. Doing multipe short PRs will be more testable.

**Comment by sultan** [comment]
https://github.com/apache/tomee/pull/936 (this PR) and https://github.com/apache/tomee/pull/928 superseded by other PRs

**Pull request closed without merging**
