### PR TITLE
TOMEE-4065 Fix to allow @LoginToContinue to be used directly in the HttpAuthenticationMechanism

### PR DESCRIPTION
**Pull request by jeanouii**
instead of requiring the interface to be implemented. Thanks Stefan Kalscheuer for reporting and for the fix

### CODE REVIEW

**Review by stklcode — APPROVED** [review]
Looks good to me. Thanks very much for the fix!

I tested my target application with both current (non-annotated) and original (annotated) implementation against the snapshot build (Microprofile with Java 17, but the result should be the very same for other flavors). Both working as expected.


Think I personally would have added a regression test case for `@FormAuthMechanismDefinition` with nested annotation, although that's already partially covered by other test suites (like https://github.com/stklcode/tomee/commit/a06dc9e600b522195874fcb515da360cd77a48bf).

**Comment by jeanouii** [comment]
I agree that it does not hurt. Can you push your changes in this branch so when I merge, your changes are included instead of me stealing your test?

**Comment by stklcode** [comment]
I do not have write permissions on this repository, so I'm afraid I cannot do this.

What I can do is (re-)create this PR from my fork or you can cherry-pick the referenced commit.

**Comment by jeanouii** [comment]
You should be able to create a PR against this branch so I can merge it

**Comment by rzo1** [comment]
@jeanouii Do we want to backport this change to 8.x, too ?

**Comment by jeanouii** [comment]
Yes we can. It should work the same way

**Comment by rzo1** [comment]
> Yes we can. It should work the same way

Ok. I will create a Jira for it, so we can pick it up.

**Pull request merged**
