### PR TITLE
Owb2.0.19

### PR DESCRIPTION
**Pull request by cocorossello**
Another PR to upgrade to OWB 2.0.18 (the explicit dependency on xbean-asm-util  is not needed now)

It also comes with a required cxf update to 3.3.7

### CODE REVIEW

**Comment by jgallimore** [comment]
We still have a number of test failures with this - here's the list of tests that fail for me:

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.558 sec <<< FAILURE!
observe(org.superbiz.cdi.events.EventTest)  Time elapsed: 4.01 sec  <<< FAILURE!
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 61.615 sec <<< FAILURE!
test(org.superbiz.schedule.events.SchedulerTest)  Time elapsed: 61.573 sec  <<< FAILURE!
[ERROR] Tests run: 1584, Failures: 21, Errors: 0, Skipped: 36, Time elapsed: 336.729 s <<< FAILURE! - in TestSuite
[ERROR] arquillianBeforeClass(org.jboss.cdi.tck.tests.context.request.event.async.RequestScopeEventAsyncTest)  Time elapsed: 40.635 s  <<< FAILURE!
[ERROR] arquillianBeforeClass(org.jboss.cdi.tck.tests.context.request.event.jms.RequestScopeEventMessageDeliveryTest)  Time elapsed: 0.294 s  <<< FAILURE!
[ERROR] arquillianBeforeClass(org.jboss.cdi.tck.tests.context.request.event.timeout.RequestScopeEventTimeoutTest)  Time elapsed: 0.246 s  <<< FAILURE!
[ERROR] resolutionWithRepeatableQualifiers(org.jboss.cdi.tck.tests.definition.qualifier.repeatable.RepeatableQualifiersTest)  Time elapsed: 0.007 s  <<< FAILURE!
[ERROR] testParameterizedResolvedType(org.jboss.cdi.tck.tests.event.metadata.EventMetadataTest)  Time elapsed: 0.004 s  <<< FAILURE!
[ERROR] testSimpleEvent(org.jboss.cdi.tck.tests.event.metadata.EventMetadataTest)  Time elapsed: 0.003 s  <<< FAILURE!
[ERROR] testGetAnnotatedType(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.002 s  <<< FAILURE!
[ERROR] testGetBean(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.002 s  <<< FAILURE!
[ERROR] testGetMember(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.002 s  <<< FAILURE!
[ERROR] testGetQualifiers(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.009 s  <<< FAILURE!
[ERROR] testGetType(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] testIsTransient(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.001 s  <<< FAILURE!
[ERROR] testSucessfulTransaction(org.jboss.cdi.tck.tests.event.observer.priority.transactional.TransactionalPriorityObserverTest)  Time elapsed: 0.022 s  <<< FAILURE!
[ERROR] testFailedTransaction(org.jboss.cdi.tck.tests.event.observer.transactional.TransactionalObserverTest)  Time elapsed: 0.033 s  <<< FAILURE!
[ERROR] testObserverFailedTransaction(org.jboss.cdi.tck.tests.event.observer.transactional.TransactionalObserverTest)  Time elapsed: 0.019 s  <<< FAILURE!
[ERROR] testSucessfullTransaction(org.jboss.cdi.tck.tests.event.observer.transactional.TransactionalObserverTest)  Time elapsed: 0.035 s  <<< FAILURE!
[ERROR] afterSuccessObserverIsNotNotifiedAfterTxRollBack(org.jboss.cdi.tck.tests.event.observer.transactional.roolback.TransactionalObserverRollbackTest)  Time elapsed: 0.022 s  <<< FAILURE!
[ERROR] notifyAcceptingConsumerNotified(org.jboss.cdi.tck.tests.extensions.configurators.observerMethod.ObserverMethodConfiguratorTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] arquillianBeforeClass(org.jboss.cdi.tck.tests.extensions.lifecycle.processInjectionPoint.ProcessInjectionPointFiredTest)  Time elapsed: 0.167 s  <<< FAILURE!
[ERROR] arquillianBeforeClass(org.jboss.cdi.tck.tests.extensions.lifecycle.processInjectionTarget.ContainerEventTest)  Time elapsed: 0.164 s  <<< FAILURE!
[ERROR] testEvent(org.jboss.cdi.tck.tests.lookup.modules.specialization.alternative.Specialization06Test)  Time elapsed: 0.002 s  <<< FAILURE!
[ERROR] Tests run: 1571, Failures: 17, Errors: 0, Skipped: 0, Time elapsed: 940.413 s <<< FAILURE! - in TestSuite
[ERROR] testEventsFired(org.jboss.cdi.tck.tests.context.request.event.timeout.RequestScopeEventTimeoutTest)  Time elapsed: 10.046 s  <<< FAILURE!
[ERROR] resolutionWithRepeatableQualifiers(org.jboss.cdi.tck.tests.definition.qualifier.repeatable.RepeatableQualifiersTest)  Time elapsed: 0.185 s  <<< FAILURE!
[ERROR] testParameterizedResolvedType(org.jboss.cdi.tck.tests.event.metadata.EventMetadataTest)  Time elapsed: 0.177 s  <<< FAILURE!
[ERROR] testSimpleEvent(org.jboss.cdi.tck.tests.event.metadata.EventMetadataTest)  Time elapsed: 0.022 s  <<< FAILURE!
[ERROR] testGetAnnotatedType(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.174 s  <<< FAILURE!
[ERROR] testGetBean(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.021 s  <<< FAILURE!
[ERROR] testGetMember(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.03 s  <<< FAILURE!
[ERROR] testGetQualifiers(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.025 s  <<< FAILURE!
[ERROR] testGetType(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.019 s  <<< FAILURE!
[ERROR] testIsTransient(org.jboss.cdi.tck.tests.event.metadata.injectionpoint.EventMetadataInjectionPointTest)  Time elapsed: 0.028 s  <<< FAILURE!
[ERROR] testSucessfulTransaction(org.jboss.cdi.tck.tests.event.observer.priority.transactional.TransactionalPriorityObserverTest)  Time elapsed: 0.311 s  <<< FAILURE!
[ERROR] testFailedTransaction(org.jboss.cdi.tck.tests.event.observer.transactional.TransactionalObserverTest)  Time elapsed: 0.294 s  <<< FAILURE!
[ERROR] testObserverFailedTransaction(org.jboss.cdi.tck.tests.event.observer.transactional.TransactionalObserverTest)  Time elapsed: 0.025 s  <<< FAILURE!
[ERROR] testSucessfullTransaction(org.jboss.cdi.tck.tests.event.observer.transactional.TransactionalObserverTest)  Time elapsed: 0.029 s  <<< FAILURE!
[ERROR] afterSuccessObserverIsNotNotifiedAfterTxRollBack(org.jboss.cdi.tck.tests.event.observer.transactional.roolback.TransactionalObserverRollbackTest)  Time elapsed: 0.171 s  <<< FAILURE!
[ERROR] notifyAcceptingConsumerNotified(org.jboss.cdi.tck.tests.extensions.configurators.observerMethod.ObserverMethodConfiguratorTest)  Time elapsed: 0.03 s  <<< FAILURE!
[ERROR] testEvent(org.jboss.cdi.tck.tests.lookup.modules.specialization.alternative.Specialization06Test)  Time elapsed: 0.025 s  <<< FAILURE!

**Comment by cocorossello** [comment]
Hi, there is something I don't understand. 

Looking at the SchedulerTest:

It works in OWB 2.0.12 and it doesn't in 2.0.16 or 17.

The stacktrace (2.0.16) is:

	at org.apache.webbeans.ee.event.TransactionalEventNotifier.registerTransactionSynchronization(TransactionalEventNotifier.java:106)
	at org.apache.openejb.cdi.OpenEJBTransactionService.registerTransactionSynchronization(OpenEJBTransactionService.java:94)
	at org.apache.webbeans.event.NotificationManager.doFireSync(NotificationManager.java:726)
	at org.apache.webbeans.event.NotificationManager.doFireEvent(NotificationManager.java:662)
	at org.apache.webbeans.event.NotificationManager.fireEvent(NotificationManager.java:646)
	at org.apache.webbeans.container.BeanManagerImpl.fireEvent(BeanManagerImpl.java:495)
	at org.apache.webbeans.container.BeanManagerImpl.fireEvent(BeanManagerImpl.java:469)
	at org.apache.webbeans.container.BeanManagerImpl.fireEvent(BeanManagerImpl.java:453)
	at org.apache.webbeans.container.InjectableBeanManager.fireEvent(InjectableBeanManager.java:109)
	at org.superbiz.schedule.events.Scheduler.timeout(Scheduler.java:54)


In 2.0.12 version is calling 

                        invokeObserverMethod(event, metadata, observer);

and in 2.0.16 is going for
                        transactionService.registerTransactionSynchronization(phase, observer, event);

So it has to do something with this commit:

https://github.com/apache/openwebbeans/commit/50a97460d3e824f298c52f98195a7d7ea5ac52af#diff-861b38d68e2a8d4b2ea08ab08d7ac29e

This is 2.0.12:

                if(phase != null && phase != TransactionPhase.IN_PROGRESS)
                {
                    if (async)
                    {
                        throw new WebBeansConfigurationException("Async Observer Methods can only use TransactionPhase.IN_PROGRESS!");
                    }

                    TransactionService transactionService = webBeansContext.getService(TransactionService.class);
                    if(transactionService != null)
                    {
                        transactionService.registerTransactionSynchronization(phase, observer, event);
                    }
                    else
                    {
                        invokeObserverMethod(event, metadata, observer);
                    }                    
                }
                else
                {
                    if (async)
                    {
                        completableFutures.add(invokeObserverMethodAsync(event, metadata, observer, notificationOptions));
                    }
                    else
                    {
                        invokeObserverMethod(event, metadata, observer);
                    }
                }

(so when phase is IN_PROGRESS it won't try to get the TransactionService)


and this is 2.0.16:


                if (phase == null || phase != TransactionPhase.IN_PROGRESS)
                {
                    invokeObserverMethod(context, observer);
                }
                else
                {
                    TransactionService transactionService = webBeansContext.getTransactionService();
                    if(transactionService != null)
                    {
                        transactionService.registerTransactionSynchronization(phase, observer, context.getEvent());
                    }
                    else
                    {
                        invokeObserverMethod(context, observer);
                    }
                }

(So when phase is IN_PROGRESS it will get the transactionService and it fails with that message).



Is this condition correct in 2.0.16?

**Comment by cocorossello** [comment]
@rmannibucau can you please take a look on latest comment?

**Comment by cocorossello** [comment]
I can confirm that changing the condition:

                if (phase == null || phase != TransactionPhase.IN_PROGRESS)

to

                if (phase == null || phase == TransactionPhase.IN_PROGRESS)

makes the SchedulerTest pass (haven't tested others)

**Comment by rmannibucau** [comment]
@cocorossello right, should be ==

**Comment by cocorossello** [comment]
We will have to wait for OWB 2.0.18

**Comment by rmannibucau** [comment]
Guess a snapshot can be already tested (just deployed it).

**Comment by cocorossello** [comment]
updated PR to use the snapshot

**Comment by cocorossello** [comment]
This cannot be merged, it needs CXF to use xbean 4.18. See org.apache.cxf.common.util.getASMClass

**Comment by cocorossello** [comment]
Can I ask for a full build to see if anything breaks. It's working in our environment (although we don't use openjpa). The upgrades are needed for jdk 15/16 support

**Comment by rmannibucau** [comment]
@cocorossello openjpa will need next release to use asm9 (it is in discussion) so you likely bring asm8+asm9 right now. Also the cxf upgrade brings a lot of jakarta, activation and jboss-rmi dependencies which should be excluded IMHO.

side note: strictly speaking OWB does not need the upgrade to support java 16 (it is coded to not need it) but tomee core and cxf do.

**Comment by cocorossello** [comment]
Thanks, then I will wait until next openjpa release and I will exclude new dependencies coming from cxf upgrade (comparing with those of tomee 8.0.4)

**Comment by cocorossello** [comment]
Hi, I've made some dependency alignments. Now the only dependency differences I can see with tomee 8.0.4 are:

reactive-streams-1.0.3.jar: New dependency from cxf, I guess it shouldn't be excluded
tomee-security-8.0.5-SNAPSHOT: New module
xbean-asm8-shaded-4.17.jar: It will be aligned to asm9 once openjpa its upgraded
xbean-asm-util-4.18.jar: New dependency from xbean.

So I will wait to upgrade openjpa and then see if build passes

**Comment by cocorossello** [comment]
Hi,
I have upgraded to use latest openjpa snapshot.

Can I request a full jenkins build to see if anything fails? Right now I can see that dependencies are fine, pulling only asm9

**Comment by rzo1** [comment]
Seems this is fixed with https://github.com/apache/tomee/commit/51610f832c8d802c7b4e0c3d42552d7f7536fd44 ?
wdyt @cocorossello ?

**Comment by cocorossello** [comment]
No. From OWB side is ok, but tomee is still using asm7 (xbean-asm7-shaded), CDIScanner will fail. JDK16 requires asm9

**Comment by cocorossello** [comment]
If you want I can try to reopen this PR doing only the xbean upgrade.

Actually,  CXF 3.4.1 is also required for java 16, I can upgrade that in another PR as well

**Comment by rzo1** [comment]
> If you want I can try to reopen this PR doing only the xbean upgrade.
> 
> Actually, CXF 3.4.1 is also required for java 16, I can upgrade that in another PR as well

Might be worth opening a JIRA and preparing a related PR, so the efforts/work is not duplicated.

**Comment by cocorossello** [comment]
https://issues.apache.org/jira/browse/TOMEE-2987
https://issues.apache.org/jira/browse/TOMEE-2988

An OpenJPA release will be required to support java 16, we can open another
issue once is released

**Comment by cocorossello** [comment]
Closing this PR since it doesn't make sense anymore

**Pull request closed without merging**
