### PR TITLE
TOMEE-2969 - Upgrade MyFaces to 2.3.8

### PR DESCRIPTION
**Pull request by tandraschko**
https://issues.apache.org/jira/browse/TOMEE-2969

### CODE REVIEW

**Review by Daniel-Dos — APPROVED** [review]

**Review by rzo1 — APPROVED** [review]
lgtm - I created a related jira and edited the PR (as we should have it in the changelogs of the next release version).

@tandraschko Is a changelog available? might be worth including it in the issue description :)

**Comment by tandraschko** [comment]
here we go :)
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=10600&version=12349324

**Comment by rzo1** [comment]
Thanks. I included it in the JIRA: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=10600&version=12349324

**Comment by cesarhernandezgt** [comment]
Thanks for the PR @tandraschko and also the review from @Daniel-Dos and @rzo1 

Indeed the 4 (*) failing tests are related to the Jenkins CI node environment since the current master and this PR locally are green as a good apple :).

[*]
org.apache.openejb.AuthentWithRequestTest.invoke
org.superbiz.calculator.CalculatorTest.remoteCallWithSslClient
org.superbiz.calculator.CalculatorTest.testCalculatorViaWsInterfaceWithUsernameTokenPlainPasswordEncrypt
org.superbiz.calculator.CalculatorTest.testCalculatorViaWsInterfaceWithSign

**Pull request merged**
