### PR TITLE
TOMEE-2313 - fixing tomee-webapp archetype.

### PR DESCRIPTION
**Pull request by cesarhernandezgt**

### CODE REVIEW

**Comment by danielsoro** [comment]
Hey @cesarhernandezgt,

What do you think to use that approach:
https://github.com/apache/tomee/blob/master/maven/tomee-webapp-archetype/pom.xml#L45

Than you can use the version from the parent and keep the version aligned with that TomEE uses.
https://github.com/apache/tomee/blob/master/pom.xml#L108

**Comment by cesarhernandezgt** [comment]
Thank you @danielsoro for the awesome approach. 
Tomorrow I'll update my PR with this improvement.

**Comment by jeanouii** [comment]
Hey @cesarhernandezgt did you get a chance to push changes or do we merge this one and you create a new PR with improvements later?

**Comment by cesarhernandezgt** [comment]
@jeanouii , please proceed with the merge of this ticket. 
I'm going to create another one with the improved version so we can move forward.

**Pull request merged**
