### PR TITLE
TOMEE-2428

### PR DESCRIPTION
**Pull request by Croway**

### CODE REVIEW

**Comment by dblevins** [comment]
Not sure if it is the recent Johnzon upgrade, but I get an exception from the test case on this one:

```
INFO - Deployed Application(path=/Users/dblevins/work/dblevins/tomee/examples/jsonb-configuration/UserServiceTest)
[
  {
    "Id":1,
    "Name":"user 1",
    "Registration":"2018 - 12 - 31"
  },
  {
    "Id":2,
    "Name":"user 2",
    "Registration":"2018 - 12 - 31"
  }
]
INFO - Undeploying app: /Users/dblevins/work/dblevins/tomee/examples/jsonb-configuration/UserServiceTest
INFO - Stopping network services
INFO - Stopping server services
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.167 sec <<< FAILURE!
get(org.superbiz.rest.UserServiceTest)  Time elapsed: 1.985 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.superbiz.rest.UserServiceTest.get(UserServiceTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.apache.openejb.junit.DeployApplication$1.call(DeployApplication.java:44)
	at org.apache.openejb.junit.DeployApplication$1.call(DeployApplication.java:40)
	at org.apache.openejb.testing.ApplicationComposers.evaluate(ApplicationComposers.java:1070)
	at org.apache.openejb.junit.DeployApplication.evaluate(DeployApplication.java:40)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

**Comment by Croway** [comment]
It's strange, i added some print statement and modified the sdf locale

**Comment by dblevins** [comment]
Here's my output.  If there are dates involved, likely there's a time zone issue.

```
INFO -      Service URI: http://127.0.0.1:4204/test/api/users ->  EJB org.superbiz.rest.UserService
INFO -               GET http://127.0.0.1:4204/test/api/users ->      List<User> users()
INFO - Deployed Application(path=/Users/dblevins/work/dblevins/tomee/examples/jsonb-configuration/UserServiceTest)
[
  {
    "Id":1,
    "Name":"user 1",
    "Registration":"1970 - 01 - 01"
  },
  {
    "Id":2,
    "Name":"user 2",
    "Registration":"1970 - 01 - 01"
  }
]
1969 - 12 - 31
INFO - Undeploying app: /Users/dblevins/work/dblevins/tomee/examples/jsonb-configuration/UserServiceTest
INFO - Stopping network services
INFO - Stopping server services
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.584 sec <<< FAILURE!
get(org.superbiz.rest.UserServiceTest)  Time elapsed: 2.406 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.superbiz.rest.UserServiceTest.get(UserServiceTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

**Comment by Croway** [comment]
Yeah the problem was a timezone issue, it should work now

**Comment by radcortez** [comment]
Seems to be passing now. Thank you @Croway. Merged!

**Pull request closed without merging**
