### PR TITLE
Faces 4.0

### PR DESCRIPTION
**Pull request by tandraschko**

### CODE REVIEW

**Comment by tandraschko** [comment]
damn, there are samples which still uses old JSF managed beans...

**Comment by jgallimore** [comment]
Currrently getting some compile errors in the Arquillian adapters/tests which I'm looking at so we can merge this in.

**Comment by tandraschko** [comment]
that would be great!

**Comment by jeanouii** [comment]
Let's close this one so we mess up with master. It's been successfully merged into the Jakarta branch

**Comment by tandraschko** [comment]
which branch is it? isnt master 10.0 the correct one?

**Comment by rzo1** [comment]
There is a PR in which the while EE10 ist happening

**Comment by rzo1** [comment]
https://github.com/apache/tomee/pull/1005

**Comment by rzo1** [comment]
These changes are integrated in https://github.com/apache/tomee/commit/bc8f54e3f5b1674b3f6ced4bd564a1c48c32c5bc

**Pull request closed without merging**
