### PR TITLE
[TOMEE-4140] Update Micro Profile to 6.0 except SmallRye Metrics

### PR DESCRIPTION
**Pull request by sultan**
Edited:

This PR needs to be merged *AFTER* PR #997
* PR #997 

[TOMEE-4140] Update Micro Profile from 5.0 to 6.0 : 
* update MP Config from 3.0.1 to 3.0.2
* update MP Health from 4.0 to 4.0.1
* update MP JWT from 3.0 to 3.1
* update MP Metrics from 3.0.1/4.0.1 to 5.0.0
* update MP Open API from 3.0 to 3.1
* update MP Rest from 3.0 to 3.0.1
* update Small Rye except the Metrics stays at 4.0.0 (instead of updating to 5.0.0)

Small Rye Metrics 5.0.0 to be done in another PR
 
I cant run the TCKs at the moment.

The TCKs might not pass after this PR.
It is precisely intended to detect the failing TCKs.

### CODE REVIEW

**Comment by sultan** [comment]
i may have been a bit agressive on the update. should i revert my changes on fault tolerance fallback (fallback to 1.0 ?)

**Comment by rzo1** [comment]
What is the difference to https://github.com/apache/tomee/pull/997 ? Seems to have an overlap (regarding MP6) ?

**Comment by sultan** [comment]
> What is the difference to #997 ? Seems to have an overlap (regarding MP6) ?

Edit:
* PR 997 will only update properties names (without changes to versions numbers)
* this PR (1009) will only update versions numbers
* this PR will have to be rebased upon 997

**Comment by rzo1** [comment]
I think, that the target should be https://github.com/apache/tomee/pull/1005

**Comment by sultan** [comment]
rebased and still intended to be merged AFTER PR https://github.com/apache/tomee/pull/997

**Comment by sultan** [comment]
@rzo1 @jeanouii rebased and ready

**Pull request merged**
