### PR TITLE
Updates the code using new API facilities

### PR DESCRIPTION
**Pull request by otaviojava**
## Updates the API

This PR has the goal to update the code using the newest API until Java 8. These improvements are:

* Use switch instead of multiple if/else: The switch is faster because there are special bytecodes that allow efficient switch statement evaluation when there are a lot of cases.

* Simplifies code using Objects.equals: It reduces the number of lines of code using the [Objects.equals ](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#equals-java.lang.Object-java.lang.Object-)also it will be faster considering the JIT factor.

* Simplifies the primitive compare using [Integer.compare](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#compare-int-int-)

* Reduces code using removeif condition in the collection.

* from the JVM specification it repleaces [`L` instead of `l`](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.10).

### CODE REVIEW

**Comment by radcortez** [comment]
Not sure if we should change the .equals() implementation.

This is mostly generated code, so the changes will be lost if we need to regenerate the equals / hashcode. I believe most people just delete the current methods and generate them again.

**Comment by brunobat** [comment]
@otaviojava Any feedback ok @radcortez comments?

**Comment by otaviojava** [comment]
Hey Bruno, I like the idea to standardize to use the new API. It simplifies and Eclipse also can generate using the new Java 7 API.

**Comment by otaviojava** [comment]
That is fine to move it forward?

**Pull request merged**
