### PR TITLE
TOMEE-4023 Comparison pages with wrong specs per profile

### PR DESCRIPTION
**Pull request by sultan**
Tomcat does not include JSTL nor the javax.security.enterprise.* packages.
The documentation should reflect that, and should have these specs into WebProfile.

### CODE REVIEW

**Review by rzo1 — APPROVED** [review]

**Comment by rzo1** [comment]
Thanks @sultan

**Comment by dblevins** [comment]
Sorry all for not seeing this PR sooner.  Here's information on Tomcat's JSTL and JASPIC implementations:

 - https://tomcat.apache.org/taglibs.html
 - https://tomcat.apache.org/tomcat-9.0-doc/config/jaspic.html

We should probably revert this change.

**Comment by rzo1** [comment]
> We should probably revert this change.

@dblevins Missed that. I will do the reverts.

**Comment by sultan** [comment]
the tomcat website indeed provides implementation for JSTL, but its not included in the tomcat server release itself.

**Comment by rzo1** [comment]
I just did the reverts as suggested by @dblevins 

Perhaps, it would be good to move this discussion towards the dev@ list, so we get consensus of what we want to display in our docs?

**Comment by dblevins** [comment]
@sultan you're right -- looks like they're not shipping it and we have a shaded version of that jar as it isn't even converted to the jakarta namespace.  Also looks like I got JASPIC and Jakarta Security mixed up.

@rzo1 sorry for the busywork

**Comment by rzo1** [comment]
@dblevins no problem.

How do we want to proceed? Looks like the changes are valid (but maybe not clear enough?) and we have a lot of confusion around it. So it can only improve :)

- (A) We recreate the PRs + the PR in site generator, ask for review on the list and move on an after some time
- (B) We recreate the PRs + the PR in site generator and move on 
- (C) Revert the revert, i.e. cherry pick the commit from the squash merge and move on

In terms of a clear git history, I would prefer (A) or (B) but we can also do (C), if this is less effort.

**Comment by sultan** [comment]
i think i wrongly moved debugging support out of tomcat into webprofile spec. so i made some minor changes that will require me to make the PRs again. i can take advantage of the new PRs to add some text to about tomcat not shipped with JSTL nor security api packages

**Pull request merged**
