### PR TITLE
TOMEE - 2524 Translate to portuguese: examples/jpa-enumerated

### PR DESCRIPTION
**Pull request by marcoantoniobferreira**
Translation to portuguese jpa-enumerated example

### CODE REVIEW

**Comment by marcoantoniobferreira** [comment]
Thanks for the review @Daniel-Dos!

**Comment by marcoantoniobferreira** [comment]
@cesarhernandezgt =)

**Comment by aasampaio3006** [comment]
Hi,
Could you check if this correct my first pull request, please.
Translate to portuguese: examples-cdi-basic
Thanks.

**Comment by Daniel-Dos** [comment]
@aasampaio3006 I did not find your PR listed

**Comment by aasampaio3006** [comment]
@Daniel-Dos , 
I believe you did something wron.
I'm sorry this was my first pull request.

See this please, url:https://github.com/aasampaio3006/tomee/commit/7ad9f2a7facff41bc5d304cbf6f1a837fdfce12c

Thanks,

**Comment by Daniel-Dos** [comment]
Hi @aasampaio3006 ,

you have to send a Pull Request request to friends to review , so that it appears here .

**Comment by aasampaio3006** [comment]
@Daniel-Dos, 

Sorry for bothering,
Could you help me, I sent an email to dev@tomee.apache.org, with this data:
PR: https://github.com/apache/tomee/pull/468
JIRA Ticket: <https://issues.apache.org/jira/browse/TOMEE-2524> https://issues.apache.org/jira/browse/TOMEE-2516

What do I need to do now?

**Comment by aasampaio3006** [comment]
@Daniel-Dos,

Sorry for bothering,
Could you help me, I sent an email to dev@tomee.apache.org, with this data:
PR: https://github.com/apache/tomee/pull/468
JIRA Ticket: https://issues.apache.org/jira/browse/TOMEE-2516

What do I need to do now?

**Comment by Daniel-Dos** [comment]
Hi @aasampaio3006 

I can help you yes .

first let's talk in that email you created, for not to pollute here  .

**Pull request merged**
