### PR TITLE
TOMEE-1566 Add '.rar' to supported suffixes for rename

### PR DESCRIPTION
**Pull request by kariem**
This replaces the patch provided in [TOMEE-1566](https://issues.apache.org/jira/browse/TOMEE-1566)

### CODE REVIEW

**Comment by AndyGee** [comment]
Hi kariem, thanks for your input. What was the motivation behind this change - Resource archive?

**Comment by kariem** [comment]
Hi Andy, 

See the [linked JIRA issue](https://issues.apache.org/jira/plugins/servlet/mobile#issue/TOMEE-1566):

> I want to deploy a maven dependency
`com.something:something-special:1.0.0:rar`
as
`something-else.rar`
via the _?name_ customization.
Unfortunately, the resulting file name is
`something-else.rar.jar`

Does this make it clear?

**Comment by kariem** [comment]
Already added to master in April by @rmannibucau: 00ce92127f6b59f027a3c3ebcf4edef383a90d2d

**Comment by AndyGee** [comment]
Thanks Romain! - Kariem, are you now happy with this, or did you need this in the 1.7.x branch?

**Comment by kariem** [comment]
Regarding my happiness with the current state: It would have only taken a click on the pull request by someone with committer privileges - no more than 5 minutes. I invested about 2 hours in the administrative overhead (besides the patch) and this had been open for about 200 days. It would not have been difficult to apply my one-liner to develop/master *and* the 1.7 branch. What do you think how happy I am?

We have a solution in place. We needed a solution about 6 months ago and I prepared a patched build and deployed it to our internal Nexus. Nobody likes that, but it works.

Please do what you think is best.

**Pull request closed without merging**
