### PR TITLE
Implement Concurrency 3.0

### PR DESCRIPTION
**Pull request by jungm**
Implements the missing gap to pass the Jakarta Concurrency 3.0 TCK including:
- Asynchronous Interceptor
- Defining Resources via annotations/web.xml
- Rework ApplicationThreadContextProvider as well as implement TxThreadContextProvider
- ManagedConnection invocation handler can now enroll already created connections in a Transaction
- ManagedThreadFactory is now wired up to ContextService

~~**Important**: This change disables SXC for parsin web.xml, I wasn't able to get the sxc-maven-plugin to run on java 17/jaxb 4 in a meaningful time, probably needs some more work~~

Thanks to @rzo1 a full build for this branch is already running [here](https://ci-builds.apache.org/job/Tomee/job/pull-request-manual/119/)

### TCK results
tck/concurrency-standalone:
```
[INFO] Tests run: 147, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 176.575 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 147, Failures: 0, Errors: 0, Skipped: 0
```

tck/concurrency-sigtest:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.950 s -- in ee.jakarta.tck.concurrent.spec.signature.SignatureTests
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Comment by rzo1** [comment]
Note: We are currently looking into SXC to avoid to having to disable it here. Current status is, that we created a Jakarta-migrated version of SXC and @jungm started to integrated this version on a separate branch. If this works out, we can update it here.

**Comment by jungm** [comment]
IMO we should not regenerate the SXC accessors in this PR, would make the diff absolutely huge and hard to review.
Think it's best to first merge both the SXC rework and this PR, then regenerate accessors on main branch

**Comment by jungm** [comment]
Also there is currently on test failure left (`org.apache.openejb.threads.ManagedScheduledExecutorServiceTest.triggerRunnableSchedule`)

**Comment by rzo1** [comment]
> IMO we should not regenerate the SXC accessors in this PR, would make the diff absolutely huge and hard to review. Think it's best to first merge both the SXC rework and this PR, then regenerate accessors on main branch

Yup. This is done in a separate PR but my comments aims to avoid merging this PR until we have re-generated the accessors ;-)

**Comment by jungm** [comment]
+1 for your preferred suggestion, just don't want this PR to become like a 10k+ diff that's impossible to review

**Comment by jungm** [comment]
I merged `main` into this branch, regenerated the SXC accessors and enabled SXC again for parsing web.xml. Also the test I mentioned in a comment above should be fixed now.

TCK is still passing on my machine and full build is green: https://ci-builds.apache.org/job/Tomee/view/tomee-10.x/job/pull-request-manual/130/

**Review by rzo1 — APPROVED** [review]

**Pull request merged**
