### PR TITLE
 TOMEE-2481 - Move code using PropertyEditors (deprectaed class) to PropertyEditorRegistry

### PR DESCRIPTION
**Pull request by danielsoro**

### CODE REVIEW

**Comment by otaviojava** [comment]
@danielsoro every time you need to use the method
` new PropertyEditorRegistry().registerDefaults().`
Why not make this method static?
`PropertyEditorRegistry.registerDefaults();`

**Comment by danielsoro** [comment]
Well.. this class is from xbean-reflect library.

Should exists reason because it is not static and I'm calling it to make sure that we have all default convert registered before get the value. 

That is what PropertyEditor was doing, but now it is totally deprectead just because it is what is recommended now: `this is all static and leaks, use PropertyEditorRegistry`

**Comment by jgallimore** [comment]
In`LocalJMXCommand` the PropertyEditorRegistry is held as a field. In other places, this is doing `PropertyEditorRegistry.registerDefaults()` when calling `getValue()`, which has to go an do a bunch of registration each time.

What do we think the lifecycle of a `PropertyEditorRegistry` should be? I did a quick search for references, which throws up `ManagedMBean`, `ActiveMQ5Factory`, `JMSProducerImpl`, and I would have thought it could be tied to the lifecycle of the components using it in each case (i.e. - make it a field).

Thoughts?

**Comment by rzo1** [comment]
@danielsoro can you resolve the conflicht in `ClaimBean.java` ?

@jgallimore I agree with your thoughs. I also think, that the `PropertyEditorRegistry` should be tied to the lifecycle of the component using it. Should we change this inside this PR or open a new JIRA and do this optimization work in a separate branch / take it as a feature? I would be +1 for the JIRA option.

**Comment by jeanouii** [comment]
Hey @rzo1 
We haven't heard from Daniel.

So if you are willing to help, I suggest you create a new PR, cherry pick what you need from this one and move on.

Does it work for you?

**Comment by rzo1** [comment]
@jeanouii Ok - i will submit a PR soon

**Comment by jgallimore** [comment]
This PR has been merged: https://github.com/apache/tomee/pull/541 - is this one still needed?

**Comment by rzo1** [comment]
@jgallimore Yes. Can be closed.

**Pull request closed without merging**
