### PR TITLE
TOMEE-2495 - Translate to portuguese: examples/jpa-eclipselink

### PR DESCRIPTION
**Pull request by marcoantoniobferreira**

### CODE REVIEW

**Comment by marcoantoniobferreira** [comment]
JIRA ticket https://issues.apache.org/jira/browse/TOMEE-2495

**Comment by Daniel-Dos** [comment]
It's very good for me.

only an change : 

change README_PT.adoc  to README_pt.adoc

thanks @marcoantoniobferreira

**Comment by marcoantoniobferreira** [comment]
Thanks Daniel, change made.

**Comment by Daniel-Dos** [comment]
great @marcoantoniobferreira  thanks.

**Comment by cesarhernandezgt** [comment]
Hi @marcoantoniobferreira 

Thank you for your contribution, in order to move forward this PR please open an email thread on the mailing list to make reference to both the Jira and the PR. 

In this way, we collaborate with the committers to move forward the contributions and follow the Apache Way "If it didn't happen on a mailing list, it didn't happen." [1] along with the recommended Apache TomEE Workflow [2].

[1] https://community.apache.org/newbiefaq.html#NewbieFAQ-IsthereaCodeofConductforApacheprojects?
[2] http://tomee.apache.org/community/contributing/workflow.html

**Comment by marcoantoniobferreira** [comment]
Ok @cesarhernandezgt! Thanks for the tip!

**Pull request merged**
