### PR TITLE
[TOMEE-4182] missing GitHub actions: adding builds for 9.x and inverting caches keys for main

### PR DESCRIPTION
**Pull request by sultan**
i saw there is:
* no GitHub actions for Pull Requests on branch 9.x (code in main branch)
* inversions of PR and non PR keys for the GitHub cache on branch main

fixed 4 files

### CODE REVIEW

**Review by rzo1 — APPROVED** [review]
we should get that in.

**Comment by sultan** [comment]
reworded the commit to include the jira issue number

**Comment by sultan** [comment]
maybe i missed the fact that such files must be on the targeted branch.
i am not sure on the conditions of execution.

lets see if its ok and if not i'll have to move files: 
branch main: main-xxx files
tomee-9.x: tomee-9.x-xxx files
tomee-8.x: tomee-8.x-xxx files

**Comment by rzo1** [comment]
thx

**Pull request merged**
